apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  namespace: blablacar
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: pgsql
  selector:
    app: user-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgres
  namespace: blablacar
spec:
  serviceName: user-postgres
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: blablacar-config
            - secretRef:
                name: blablacar-secret
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi